version: '3'

services:
  api:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - 'backend'
    container_name: 'api'
    depends_on:
      - postgres
      - redis
    ports:
      - '8080:8080'

  postgres:
    restart: always
    image: 'postgres:latest'
    container_name: postgres
    networks:
      - 'backend'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=movie
      - POSTGRES_USER=movie
      - POSTGRES_PASSWORD=movie
    volumes:
      - './postgres-data:/var/lib/postgresql/data'
      - './deploy/:/docker-entrypoint-initdb.d/'

  redis:
    restart: always
    image: 'redis:latest'
    container_name: 'redis'
    networks:
      - 'backend'
    ports:
      - '6379:6379'

networks:
  backend:
    driver: bridge